// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

namespace WebApi.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20211202053646_createRetailTables")]
    partial class createRetailTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("WebApi.Entities.Households", b =>
                {
                    b.Property<int>("Hshd_Num")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age_range")
                        .HasColumnType("TEXT");

                    b.Property<string>("Children")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homeowner_desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hshd_composition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hshd_size")
                        .HasColumnType("TEXT");

                    b.Property<string>("Income_range")
                        .HasColumnType("TEXT");

                    b.Property<string>("Loyality_flag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marital_status")
                        .HasColumnType("TEXT");

                    b.HasKey("Hshd_Num");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("WebApi.Entities.Products", b =>
                {
                    b.Property<int>("Product_num")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand_ty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comodity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Natural_organic_flag")
                        .HasColumnType("TEXT");

                    b.HasKey("Product_num");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApi.Entities.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Basket_num")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hshd_Num")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Product_num")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purchase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Spend")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stock_r")
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week_num")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hshd_Num");

                    b.HasIndex("Product_num");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmaailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Entities.Transactions", b =>
                {
                    b.HasOne("WebApi.Entities.Households", "Households")
                        .WithMany("Transactions")
                        .HasForeignKey("Hshd_Num")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Products", "Products")
                        .WithMany("Transactions")
                        .HasForeignKey("Product_num")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
